[book]
authors = ["innocentzero"]
language = "en"
multilingual = false
src = "src"
title = "My Home"

[output.html]
default-theme = "ayu"
#preferred-dark-theme = "ayu"
curly-quotes = true
mathjax-support = true
no-section-label = false
additional-css = ["./src/custom.css"]
#input-404 = "not-found.md"

[output.html.fold]
enable = true    # whether or not to enable section folding
level = 0         # the depth to start folding

[output.html.playground]
editable = false         # allows editing the source code
copyable = true          # include the copy button for copying code snippets
copy-js = true           # includes the JavaScript for the code editor
line-numbers = true     # displays line numbers for editable code
runnable = false          # displays a run button for rust code

[rust]
edition = "2021"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
